version: '3.9'
services:
  backend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -lc "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
      - FYNIX_ALERTS_INTERVAL=15
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8000/api
    command: sh -lc "corepack enable && pnpm i && pnpm dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
