version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fynix
      POSTGRES_PASSWORD: fynix
      POSTGRES_DB: fynix
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  backend:
    build: ./backend
    env_file: ./backend/.env.example
    environment:
      POLYGON_KEY: ${POLYGON_KEY}
      ALPHAVANTAGE_KEY: ${ALPHAVANTAGE_KEY}
      FINNHUB_KEY: ${FINNHUB_KEY}
      COINGECKO_KEY: ${COINGECKO_KEY}
      CMC_KEY: ${CMC_KEY}
      NEWSAPI_KEY: ${NEWSAPI_KEY}
      MARKETAUX_KEY: ${MARKETAUX_KEY}
      FMP_KEY: ${FMP_KEY}
    ports: ["8000:8000"]
    depends_on: [db, redis]
  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    ports: ["3000:3000"]
    depends_on: [backend]

  ollama:
    image: ollama/ollama:latest
    container_name: fynix_ollama
    restart: unless-stopped
    ports: ["11434:11434"]
    volumes:
      - ollama_models:/root/.ollama
    # Optionally preload a model on first run:
    # entrypoint: ["bash","-lc","ollama serve & sleep 2 && ollama pull llama3.1 && tail -f /dev/null"]
volumes:
  ollama_models:
