services:
  backend:
    build:
      context: ./backend
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    environment:
      - FYNIX_JWT_SECRET
      - FYNIX_JWT_TTL_MIN
      - FRONTEND_ORIGIN
      - REDIS_URL
      - OPENAI_API_KEY
      - OPENAI_BASE
      - OPENAI_MODEL
      - ALPHAVANTAGE_API_KEY
      - FINNHUB_API_KEY
      - POLYGON_API_KEY
      - COINGECKO_API_KEY
      - COINMARKETCAP_API_KEY
      - NEWSAPI_KEY
      - MARKETAUX_API_KEY
      - FMPREP_API_KEY
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    # dev-friendly command; uses volumes to live-reload
    command: sh -c "corepack enable && pnpm i && pnpm dev --host 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8000/api
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
